### ISSUE TITLE
Route `host` can't be managed using `oc apply`, as currently done by `bcdk`, causing deployment-time pipeline failures.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/bcdk#30]
Currently, `bcd` manages/deploys OpenShift resources using `oc apply`, which works in general, but does not work for resources with read-only attributes such as route `host`.  The first application works, but subsequent attempts (further deploys) fail.  We probably need some way to indicate that a given resource should be managed using a different approach.

**Comment by lukegonis** [comment]
Closing as this is no longer relevant to the Platform Services team
