### ISSUE TITLE
building a PR from child branch to a parent branch (not master) fails 

### ISSUE THREAD

**Issue by RajvirBains** [BCDevOps/bcdk#45]
This could be something I am doing wrong and will close the issue once have determined the root cause.

I am deploying BCDK and testing PR from a branch that is two levels from the master. BCDK changes are not in master yet.

master > bcdk-deployment-for-agri > child-bcdk-deployment-for-agri
**PR405 bcdk-deployment-for-agri to master: working fine**. All the BCDK changes are here. Works fine and create PR based dev pods and TEST also works.
**PR406 child-bcdk-deployment-for-agri > bcdk-deployment-for-agri.** This one tries to start a build on Jenkins (i.e. webhook works), but it **fails right away due to some HEAD issue** which shows up in GitHub but the Jenkins build disappears. No log of any sort.

I wonder if I am running into this because my Jenkins changes are not in the master branch yet.

GitHub shows this: **continuous-integration/jenkins/pr-head — This commit cannot be built** 
https://nmp-jenkins-agri-nmp-tools.pathfinder.gov.bc.ca/blue/organizations/jenkins/_jenkins/detail/PR-406/1/pipeline

cvarjao, could you please take a look at https://github.com/bcgov/agri-nmp/pull/406 and see what I could be missing? Feel free to do an empty commit to trigger.

**Comment by patricksimonian** [comment]
I believe whats going on is that the jenkins job will ignore PR's that are not against master. @cvarjao  please correct me if im wrong here. 

As a work around you can leverage the `pipeline-cli` scripts directly by running them on your workstation.

**Comment by RajvirBains** [comment]
so far it seems that what I ran into was just a glitch as 4 try worked ok without any changes. maybe more testing is needed.

**Comment by patricksimonian** [comment]
Marking this issue as resolved. If you can find a way to reproduce the error please make an issue so we can look into it :)

**Comment by RajvirBains** [comment]
I did some more testing on the issue https://github.com/BCDevOps/bcdk/issues/45 and see that the issue is related to empty commits not building. I tested it about 3 times last night where I would submit a fake commit using --allow-empty which will fail to trigger a build, but then an actual change with a commit did. It might be good if someone else can also test this. We can reopen the issue.
