### ISSUE TITLE
Need to add testing frameworks

### ISSUE THREAD

**Issue by jas29** [BCDevOps/bcdk#65]
Need to add testing frameworks for bcdk, such as jest, mocha/chai and code climate

**Comment by cvarjao** [comment]
@jas29, `yeoman` already comes with its own opinionated testing framework (jest):
https://yeoman.io/authoring/testing.html

see `packages.json` for the `test` script

**Comment by patricksimonian** [comment]
code climate has been authorized as well. Closing this issue :)
